import axiosInstance from './axiosInstance';

/**
 * Transfer API calls — relative to /api/v1.
 *
 * Backend endpoint (see report.md §5.2):
 *   POST /transfers  → 201 Created, returns TransferResponse
 *
 * There is NO global GET /transactions endpoint.
 * Use getAccountTransactionsApi from accounts.js to get per-account history.
 *
 * FR-05: Every request must include an idempotencyKey (UUID v4) generated by the frontend.
 */

/**
 * Initiates a fund transfer.
 * @param {{ fromAccountId: number, toAccountId: number, amount: number, idempotencyKey: string }} payload
 */
export const initiateTransferApi = (payload) =>
  axiosInstance.post('/transfers', payload);
